# Generated by Django 3.2.4 on 2021-06-26 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCat', models.CharField(max_length=20, verbose_name='Nombre categoria')),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreP', models.CharField(max_length=25, verbose_name='Nombre producto')),
                ('descripcionP', models.CharField(max_length=700, verbose_name='Descipcion producto')),
                ('miniDescripcion', models.CharField(max_length=30, verbose_name='Descripcion abreviada')),
                ('precioP', models.IntegerField(verbose_name='Precio producto')),
                ('nombreU', models.CharField(max_length=20, verbose_name='Nombre de usuario')),
                ('emailU', models.CharField(max_length=30, verbose_name='Correo de usuario')),
                ('telefonoU', models.CharField(blank=True, max_length=12, verbose_name='Teléfono de usuario')),
                ('instagramU', models.CharField(blank=True, max_length=20, verbose_name='Instagram de usuario')),
                ('facebookU', models.CharField(blank=True, max_length=25, verbose_name='Facebook de usuario')),
                ('twitterU', models.CharField(blank=True, max_length=25, verbose_name='Twitter de usuario')),
                ('whatsappU', models.CharField(blank=True, max_length=12, verbose_name='Whatsapp de usuario')),
                ('categoriaP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
