# Generated by Django 3.2.4 on 2021-06-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_imgp'),
    ]

    operations = [
        migrations.CreateModel(
            name='modeloContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreC', models.CharField(max_length=20, verbose_name='Nombre de contacto')),
                ('correoC', models.EmailField(max_length=254, verbose_name='Correo de contacto')),
                ('mensajeC', models.TextField(verbose_name='Mensaje de contacto')),
            ],
        ),
    ]
