# Generated by Django 3.2.4 on 2021-06-27 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_modelocontacto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='modeloContacto',
            new_name='contacto',
        ),
    ]
